# file: roles/ssh/defaults/main.yml

# add AllowUsers: username to restrict user logins
ssh_settings:
  Port: "22"
  Protocol: "2"
  UsePrivilegeSeparation: "yes"
  KeyRegenerationInterval: "3600"
  ServerKeyBits: "768"
  SyslogFacility: "AUTH"
  LogLevel: "INFO"
  LoginGraceTime: "30" # default 120
  PermitRootLogin: "no"
  StrictModes: "yes"
  RSAAuthentication: "yes"
  PubkeyAuthentication: "yes"
  IgnoreRhosts: "yes"
  RhostsRSAAuthentication: "no"
  HostbasedAuthentication: "no"
  PermitEmptyPasswords: "no"
  ChallengeResponseAuthentication: "no"
  PasswordAuthentication: "no"
  X11Forwarding: "no" # may wish to turn this off for security purposes it was defaulted to yes
  X11DisplayOffset: "10"
  PrintMotd: "no"
  PrintLastLog: "yes"
  TCPKeepAlive: "yes"
  AcceptEnv: "LANG LC_*"
  Subsystem: "sftp /usr/lib/openssh/sftp-server"
  UsePAM: "yes"
  UseDNS: "no"
  ClientAliveInterval: "300" # default 1750
  ClientAliveCountMax: "0"
  DebianBanner: no
  Banner: /etc/issue.net
#  AllowGroups: admin vagrant # causes errors when enabled
  MaxSessions: "3"
  MaxStartups: "10:30:60"
