# https://github.com/jprichardson/ansible-redis/blob/master/main.yml
# https://github.com/bennojoy/ansible-roles/tree/master/redis
---
# Install redis
- name: Install and configure Redis
  action: apt name=redis-server state=latest
  sudo: true
  notify: Restart Redis


# if want to open up redis to other IP addresses/ as well must adjust bind IPs in /etc/redis/redis.conf
# https://github.com/slickage/ansible-rails/blob/master/roles/database/tasks/redis.yml


# Ensure Redis server is running
- name: "Ensure Redis server is running"
  sudo: yes
  action: service name=redis-server state=started
